name: CI

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release

